### ISSUE TITLE
Expiration time measure unit.

### ISSUE THREAD

**Issue by edgarecko7** [kamerk22/adonis-url-signer#5]
Hello, i've implemented this tool in order to set a time expiration when a user requests a reset password link and seems to work just fine.

But i would like the URL lasted only 5 minutes instead.

Do i have to change the code or is it possible to pass a decimal number like :
.17
.08
or so?

Thanks in advance and also thanks for this tool.

**Comment by kamerk22** [comment]
@edgarecko7 You can pass the decimal 0.0833 which is equivalent for 5 minutes.
 
Currently code is working based on Hour value. However, you can use any value just convert it to hours eq.

**Comment by edgarecko7** [comment]
Working fine after passing 0.0833 to the defaultExpirationTimeInHour property in the config and lasting only ~5 minutes.

Thank you very much.
